# Generated by Django 2.2.7 on 2019-11-29 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0006_auto_20191129_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='voters',
            field=models.ManyToManyField(through='polls.Vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
