# Generated by Django 2.2.7 on 2019-11-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_question_voters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='voters',
        ),
    ]
