# Generated by Django 2.2.7 on 2019-11-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('polls', '0010_auto_20191129_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
